FROM alpine:3.5

MAINTAINER Pierrick Brossin <github@bs-network.net>

# exposed ports
EXPOSE  2080
EXPOSE  8888

RUN apk --no-cache add nodejs \
 && npm install -g nodemon \
 && mkdir -p /src/backend /src/frontend

# app sources
COPY ./src/package.json /src/

# install app dependencies
RUN cd /src \
 && npm install

WORKDIR /src/backend/

CMD ["nodemon", "/src/backend/server.js"]
